/*
------------------------------
CANC Armed Forces
------------------------------
*/

/datum/skills/canc_soldier
	name = "Soldier"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)

/datum/skills/canc_soldier/gunner
	name = "Machinegunner"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_SPEC = SKILL_SPEC_SMARTGUN,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)

/datum/skills/canc_soldier/medic
	name = "Field Medic"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)

/datum/skills/canc_soldier/sl
	name = "Squad Leader"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/canc_soldier/pl
	name = "Platoon Leader"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/*
------------------------------
CANC Militia
------------------------------
*/

/datum/skills/canc_soldier/militia
	name = "Militia"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)

/datum/skills/canc_soldier/militia/medic
	name = "Militia Medic"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)


/datum/skills/canc_soldier/militia/sl
	name = "Militia Leader"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)

/datum/skills/canc_soldier/militia/trained
	name = "Militia"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_UNTRAINED,
	)

/*
------------------------------
CANC SOF
------------------------------
*/

/datum/skills/canc_soldier/sof
	name = "SOF Operative"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_SPEC = SKILL_SPEC_ALL,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
	)

/datum/skills/canc_soldier/sof/medic
	name = "SOF Medic"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_SPEC = SKILL_SPEC_ALL,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
	)

/datum/skills/canc_soldier/sof/sl
	name = "SOF Leader"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_SPEC = SKILL_SPEC_ALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
	)

/*
------------------------------
CANC Other
------------------------------
*/

/datum/skills/canc_soldier/pilot
	name = "Pilot"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
	)

/datum/skills/canc_soldier/crewman
	name = "Crewman"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/canc_soldier/officer
	name = "Officer"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_SPEC = SKILL_SPEC_UNTRAINED,
	)
