// SS220 EDIT: round cinematics outcome constants for upstream use
#define ROUND_CINEMATICS_OUTCOME_AUTO 0
#define ROUND_CINEMATICS_OUTCOME_MARINE_VICTORY 1
#define ROUND_CINEMATICS_OUTCOME_MARINE_DEFEAT 2
#define ROUND_CINEMATICS_OUTCOME_INCONCLUSIVE 3
