/datum/skills/combat_medic/odst
	name = "ODST Corpsman"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/unsc/spartan
	name = "UNSC, Spartan"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_DEFAULT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_DEFAULT,
		SKILL_CQC = SKILL_CQC_MAX,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_GUN_HO = SKILL_GUN_HO_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
	)
