/datum/world_edit_manager/proc/build_ui_data_payload(mob/user = null)
	var/has_generator = (current_definition && current_generator) ? TRUE : FALSE
	append_runtime_trace("ui_payload:ui_fields:start")
	var/list/ui_fields = get_normalized_ui_fields()
	append_runtime_trace("ui_payload:ui_fields:done", "count=[length(ui_fields)]")
	var/requires_preview = current_generator?.requires_preview_before_apply ? TRUE : FALSE
	append_runtime_trace("ui_payload:placement_modes:start")
	var/list/placement_modes = build_placement_mode_options()
	append_runtime_trace("ui_payload:placement_modes:done", "count=[length(placement_modes)]")
	append_runtime_trace("ui_payload:placement_shapes:start")
	var/list/placement_shapes = build_placement_shape_options()
	append_runtime_trace("ui_payload:placement_shapes:done", "count=[length(placement_shapes)]")
	append_runtime_trace("ui_payload:shape_fields:start")
	var/list/placement_shape_fields = build_current_placement_shape_fields()
	append_runtime_trace("ui_payload:shape_fields:done", "count=[length(placement_shape_fields)]")
	append_runtime_trace("ui_payload:click_state:start")
	var/click_mode_active = sync_click_intercept_state()
	append_runtime_trace("ui_payload:click_state:done", "active=[click_mode_active]")
	append_runtime_trace("ui_payload:generator_specific:start")
	var/list/generator_payload = has_generator ? current_generator.get_ui_payload(current_params) : list()
	append_runtime_trace("ui_payload:generator_specific:done", "present=[length(generator_payload)]")
	var/list/data = list()

	append_runtime_trace("ui_payload:generator:start")
	apply_ui_payload(data, build_generator_ui_payload(has_generator, ui_fields, requires_preview, generator_payload))
	append_runtime_trace("ui_payload:generator:done")
	append_runtime_trace("ui_payload:placement:start")
	apply_ui_payload(data, build_placement_ui_payload(click_mode_active, placement_modes, placement_shapes, placement_shape_fields))
	append_runtime_trace("ui_payload:placement:done")
	append_runtime_trace("ui_payload:preset:start")
	apply_ui_payload(data, build_preset_ui_payload())
	append_runtime_trace("ui_payload:preset:done")
	append_runtime_trace("ui_payload:blueprint:start")
	apply_ui_payload(data, build_blueprint_ui_payload(user))
	append_runtime_trace("ui_payload:blueprint:done")
	append_runtime_trace("ui_payload:feedback:start")
	apply_ui_payload(data, build_feedback_ui_payload())
	append_runtime_trace("ui_payload:feedback:done")
	append_runtime_trace("ui_payload:actionability:start")
	apply_ui_payload(data, build_actionability_ui_payload(has_generator, requires_preview, click_mode_active))
	append_runtime_trace("ui_payload:actionability:done")
	append_runtime_trace("ui_payload:history:start")
	apply_ui_payload(data, build_history_ui_payload())
	append_runtime_trace("ui_payload:history:done")
	return data
