/mob/living/carbon/human/Login()
	. = ..()
	if(species)
		species.handle_login_special(src)
	if(selected_ability)
		set_selected_ability(null)
	if(stat == UNCONSCIOUS)
		spawn(1)
			play_opening_sequence()
