#define WORLD_EDIT_VISUAL_STATUS_SUPPORTED "supported"
#define WORLD_EDIT_VISUAL_STATUS_LOCKED "locked"
#define WORLD_EDIT_VISUAL_STATUS_FAILED "failed"
#define WORLD_EDIT_VISUAL_STATUS_ERROR "error"

#define WORLD_EDIT_VISUAL_STAGE_LOAD_CASE "load_case"
#define WORLD_EDIT_VISUAL_STAGE_CANVAS_SETUP "canvas_setup"
#define WORLD_EDIT_VISUAL_STAGE_SUPPORT_CHECK "support_check"
#define WORLD_EDIT_VISUAL_STAGE_PREVIEW "preview"
#define WORLD_EDIT_VISUAL_STAGE_APPLY "apply"
#define WORLD_EDIT_VISUAL_STAGE_POST_EMIT_VALIDATE "post_emit_validation"
#define WORLD_EDIT_VISUAL_STAGE_EXPORT "export"
#define WORLD_EDIT_VISUAL_STAGE_UNDO "undo"

#define WORLD_EDIT_VISUAL_DEFAULT_INBOX "tools/world_edit_visual/inbox"
#define WORLD_EDIT_VISUAL_DEFAULT_OUT "tools/world_edit_visual/out"
#define WORLD_EDIT_VISUAL_FALLBACK_Z 1
#define WORLD_EDIT_VISUAL_MAX_CANVAS_SIZE 128
#define WORLD_EDIT_VISUAL_MIN_CANVAS_SIZE 16
