// t1
#define PONY_XENO_CASTE_PEGASUS_SKIRMISHER "Pegasus Skirmisher"

// t2
#define PONY_XENO_CASTE_EARTH_BRUISER "Earth Bruiser"
#define PONY_XENO_CASTE_UNICORN_CASTER "Unicorn Caster"

// t0 / royal
#define PONY_XENO_CASTE_ALICORN_MATRIARCH "Alicorn Matriarch"

#define ALL_PONY_XENO_CASTES list(PONY_XENO_CASTE_PEGASUS_SKIRMISHER, PONY_XENO_CASTE_EARTH_BRUISER, PONY_XENO_CASTE_UNICORN_CASTER, PONY_XENO_CASTE_ALICORN_MATRIARCH)
